### ISSUE TITLE
Set 'Active' field to default 'false'

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-database#13]
Trees should be approved before they show up on the map.

If we set the 'active' field to default to 'false' this will remove this issue. 

The problem is that people will not be able to see their trees once they are uploaded unless we are processing the data quickly.  

We should probably be held off until we are able to process data in a timely manner.

**Comment by deepwinter** [comment]
This isn't something we are going to do any time soon since approve/reject is not approaching realtime currently.
