### ISSUE TITLE
Add `Tags Table` and add `Tags Field` to `Trees Table`

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-database#17]
Each 'tree_id' will be given a number of tags.
### Tags: 

- Seeding, direct seedling, Pruned/tied (FMNR), New tree, old tree (>2 years)

- Approve tags "simple leaf, complex leave, acacia like, conifer, fruit, mangrove, palm, timber"

- Reject Tags, "Not a tree, Not an approved tree, blurry photo, Dead, duplicate photo, flag user! Flag tree for contact/review" 

Question: 'Flag user" seems like is should be a field in the planter table.

**Comment by deepwinter** [comment]
I did this differently using enumerated fields since this allows us to validate that only enabled tag names are used.  Generic tagging can still be something we do if necessary, but it leads to errors and needs complex querying.
