### ISSUE TITLE
Create a CSV of 200 tokens of "good" trees from the following planter ids:

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-database#49]
1108
1168
1167
1441
1544
1571

'Good' trees are approved = true, and actual pictures of seedlings (not something else).  Many trees in this set are not trees, and are tagged (the tags tables) as 'food aid' or 'FOOD AID'

**Comment by deepwinter** [comment]
a suggested option for workflow: We can filter in the admin panel by planter and tag manually the good ones and then select them with a query? @sebastiangaertner 

another workflow would involve just using direct database access, if the operator prefers

**Comment by Davidezrajay** [comment]
Workflow: 
1. used DeBeaver to search trees table with above user
2. created CSV of approved trees
3. Created demo wallet
4. created tokens to that wallet
5. reviewed wallet by clicking on the web map to see that they were all 'good trees'
