### ISSUE TITLE
Add Species_Id to trees table

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-database#6]

**Comment by deepwinter** [comment]
is this a text field?  The correct way to do this is to create a species table, and then populate each tree with an integer linking it to the species.  Is this what you want?

**Comment by Davidezrajay** [comment]
In the 'trees' table add 'species_id' integer field. 

The existing tree_species table: 
-  'id' (123...)
-  'name' (abc...)
-  'value factor' (123...)

Delete fields 'desc' and 'active'

**Comment by deepwinter** [comment]
Done
