### ISSUE TITLE
Payment_table created on database

### ISSUE THREAD

**Issue by petersenpdx** [Greenstand/treetracker-database#7]
Currently, we do not have a table on the database for any payments that are created for planters. This would be the first step in moving towards a more stream lined (possibly automated) system. 

Suggested Table Fields: 
- **payment_id** - primary key and unique identifier of payment
- **user_id** - to identify which user was paid 
- **date_paid** - timestamp of the transaction 
- **certificate_paid** (optional) - to know what certificate paid for the individual. Since the 
    certificate might be changing on the tree_id, this could be used as a snap-shot of what 
    certificate paid for the planter at that time. 
- **tree_amt**  - The amount of trees that were paid for. 
- **usd_amt** - The amount of US dollars that were paid.
- **local_amt** - The local currency that was paid. 
- **paid_by** - who paid the individual. 

This would work best to add an additional field of payment_id to the trees_table.

**Comment by deepwinter** [comment]
I don't understand certificate_paid here, can you explain?

**Comment by petersenpdx** [comment]
Certificate_paid would indicate the certificate_id at the time of payment. This would only be useful for auditing purposes -to see what certificate_id (donor) paid for  what planter, since there is no token (tree_id) transaction history (if we are using a token process).

**Comment by Davidezrajay** [comment]
Let's remove the certificate_id from this ticket and push it through.

**Comment by Davidezrajay** [comment]
We will also need a Valid_User Table. So the user_id in this field should eventually be pulled from the Valid user table, which would be the 'master account' for the planter.
